project_id = "twyzhndqxynbhgmqshuz"

[functions.loaderio-verification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-setup-intent]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.delete-payment-method]
verify_jwt = true

[functions.list-payment-methods]
verify_jwt = true

[functions.provider-financial-data]
verify_jwt = true

[functions.send-notifications]
verify_jwt = false

[functions.pay-with-saved-card]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true

[functions.provider-heartbeat]
verify_jwt = true

[functions.online-providers]
verify_jwt = true

[functions.create-chamado]
verify_jwt = true

[functions.toggle-provider-online]
verify_jwt = true

[functions.pending-chamados]
verify_jwt = true

[functions.check-pending-fees]
verify_jwt = true

[functions.record-service-fee]
verify_jwt = true

[functions.notify-admin-payment]
verify_jwt = true

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-otp-reset-password]
verify_jwt = false

[functions.notify-admin-suspicious]
verify_jwt = true

[functions.generate-notification-text]
verify_jwt = true

[functions.generate-notification-image]
verify_jwt = true
